In [15]:
import numpy as np
import cv2
import matplotlib.pyplot as plt 

In [3]:
img = cv2.imread('/Users/jinger/Downloads/lenna.png')
#cv2.startWindowThread()
cv2.imshow('lenna', img)
#key = cv2.waitKey()
#if key == 27:
#    cv2.destroyAllWindows()
cv2.waitKey(0) # 按任意键关闭显示图片
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1

In [ ]:
# Gaussian Kernel Effect
g_img = cv2.GaussianBlur(img,(7,7),5)
cv2.imshow('gaussian_blur_lenna', g_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [3]:
# 图像变更模糊，因为范围更大，平均效果更明显
g_img = cv2.GaussianBlur(img,(17,17),5)
cv2.imshow('gaussian_blur_lenna', g_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [ ]:
# 图像更清晰，因为方差更小，高斯图像更尖锐，中心点起的作用更大
g_img = cv2.GaussianBlur(img,(7,7),1)
cv2.imshow('gaussian_blur_lenna', g_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [26]:
# 来看看高斯核
kernel = cv2.getGaussianKernel(7, 5)
print(kernel)


[[0.12895603]
 [0.14251846]
 [0.15133131]
 [0.1543884 ]
 [0.15133131]
 [0.14251846]
 [0.12895603]]


In [6]:
# 为啥一维，因为一维运算快
# 理论解释
# 用显式地代码看隐式地高斯和显示地分步高斯地效果
g1_img = cv2.GaussianBlur(img,(7,7),5)
g2_img = cv2.sepFilter2D(img, -1, kernel, kernel) # ori, depth, kernelX, kernelY
cv2.imshow('g1_blur_lenna', g1_img)
cv2.imshow('g2_blur_lenna', g2_img)
cv2.waitKey(0) # 按任意键关闭显示图片
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1

In [14]:
######## Other Applications #########
# 2nd derivative: laplacian （双边缘效果）
kernel_lap = np.array([[0, 1, 0], [1, -4, 1], [0, 1, 0]], np.float32)
lap_img = cv2.filter2D(img, -1, kernel=kernel_lap)
cv2.imshow('lap_lenna', lap_img)
cv2.waitKey(0) # 按任意键关闭显示图片
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1

In [7]:
# 应用： 图像锐化 = edge+ori
# app: sharpen
# 图像+edge=更锐利地图像，因为突出边缘
kernel_sharp = np.array([[0, 1, 0], [1, -6, 1], [0, 1, 0]], np.float32) 
lap_img = cv2.filter2D(img, -1, kernel=kernel_sharp)
cv2.imshow('sharp_lenna', lap_img)
cv2.waitKey(0) # 按任意键关闭显示图片
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1

In [14]:
# 这样不对，因为，周围有4个1，中间是-3，虽然有边缘效果，但是周围得1会使得原kernel有滤波效果，使图像模糊；
# 解决：所以取kernel_lap得相反数，再加上原图像，这样突出了中心像素，效果类似于小方差的高斯，所以
#      可以既有边缘效果，又保留图像清晰度
kernel_sharp = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]], np.float32) 
lap_img = cv2.filter2D(img, -1, kernel=kernel_sharp)
cv2.imshow('sharp_lenna', lap_img)
cv2.waitKey(0) # 按任意键关闭显示图片
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1

In [ ]:
# 对于以上三段代码,kernel不一样，结果其实都是彩色图像
# 但是大部分是0，肉眼看不出来是彩色的

In [7]:
# 更“凶猛”的边缘效果
# 不仅考虑x-y方向上的梯度，同时考虑了对角线方向上的梯度
kernel_sharp = np.array([[1, 1, 1], [1, -8, 1], [1, 1, 1]], np.float32) 

In [8]:
######## Edge #########
# x轴
edgex = np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]], np.float32)
sharp_img = cv2.filter2D(img, -1, kernel=edgex)
cv2.imshow('edgex_lenna', sharp_img)
cv2.waitKey(0) # 按任意键关闭显示图片
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1

In [9]:
# y轴
edgey = np.array([[-1, 0, -1], [-2, 0, 2], [-1, 0, 1]], np.float32)
sharpy_img = cv2.filter2D(img, -1, kernel=edgey)
cv2.imshow('edgex_lenna', sharp_img)
cv2.imshow('edgey_lenna', sharpy_img)
cv2.waitKey(0) # 按任意键关闭显示图片
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1

In [19]:
######### 角点 ###########
img = cv2.imread('/Users/jinger/Downloads/corner.jpg')
print(img.shape)
#img = cv2.resize(img, (640, 480))
img_gray = np.float32(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY))
print(img_gray)

(384, 512, 3)
[[ 88.  87.  85. ...  86.  86.  86.]
 [ 88.  87.  85. ...  83.  84.  84.]
 [ 87.  86.  85. ...  80.  82.  83.]
 ...
 [109. 109. 109. ... 176. 176. 176.]
 [109. 109. 109. ... 175. 175. 175.]
 [109. 109. 109. ... 174. 174. 174.]]


In [28]:
#    img - 数据类型为 float32 的输入图像。
#　　 blockSize - 角点检测中要考虑的领域大小。
#　   ksize - Sobel 求导中使用的窗口大小
#　　  k - Harris 角点检测方程中的自由参数,取值参数为 [0,04,0.06].
img_harris = cv2.cornerHarris(img_gray, 3, 3, 0.04)
cv2.imshow('img_harris ', img_harris)
cv2.waitKey(0) # 按任意键关闭显示图片
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1

In [23]:
# 没法看原因：1. float类型； 2. img_harris本质上是每个pixel对于Harris函数的响应值
# 没有看的价值
print(img_harris)

# 为了显示清楚
img_harris = cv2.dilate(img_harris , None)

[[-1.0030746e-02 -7.4691296e-02 -1.2839507e+00 ... -2.3615589e+01
  -7.5173626e+00 -4.1248460e+00]
 [ 1.0289352e+00  8.5234368e-01 -7.6335847e-01 ... -4.0810585e+00
   2.0309725e+00  1.9944453e+00]
 [ 1.2411652e+00  1.4924383e+00 -2.1512347e-01 ...  3.6173214e+01
   2.7608641e+01  1.8181904e+01]
 ...
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00 ...  5.3360361e-01
   5.2441168e-01  4.9382702e-02]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00 ...  9.0769798e-02
  -2.7401656e-02 -1.4293985e-01]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00 ...  1.9131941e-01
  -2.0528552e-01 -3.5555562e-01]]


In [24]:
thres = 0.05 * np.max(img_harris)
img[img_harris > thres] = [0, 0, 255]
cv2.imshow('img_harris ', img)
cv2.waitKey(0) # 按任意键关闭显示图片
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1

In [29]:
########### SIFT ###########
img = cv2.imread('/Users/jinger/Downloads/lenna.png')
# create sift class
sift = cv2.xfeatures2d.SIFT_create()
# detect SIFT
kp = sift.detect(img,None)   # None for mask
# compute SIFT descriptor
kp,des = sift.compute(img,kp)
print(des.shape)
img_sift= cv2.drawKeypoints(img,kp,outImage=np.array([]), flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
cv2.imshow('lenna_sift.jpg', img_sift)
cv2.waitKey(0) # 按任意键关闭显示图片
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

(238, 128)


-1